version: "3.9"

networks:
  web:

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "8080:8080" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`127.0.0.1`) && PathPrefix(`/traefik`)"
      - "traefik.http.routers.api.rule=Host(`172.201.218.98`) && PathPrefix(`/api`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    networks:
      - web
    restart: always

  postgres:
    image: ghcr.io/ubehrmann/db_crud_server:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    networks:
      - web
    restart: always

  app:
    image: ghcr.io/ubehrmann/crud_server:latest
    container_name: crud-server
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/mydb
      DB_USER: user
      DB_PASSWORD: password
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.api.loadbalancer.server.port=7000"
      # Optional: Uncomment the following lines if the backend doesn't expect `/api` in the path
      - "traefik.http.middlewares.strip-api.stripprefix.prefixes=/api"
      - "traefik.http.routers.api.middlewares=strip-api"
    networks:
      - web
    restart: always
