services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    restart: always

  app:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - "7000:7000"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/mydb
      DB_USER: user
      DB_PASSWORD: password
