FROM timescale/timescaledb:latest-pg14
# Copy init scripts
COPY 01_createTables.sql /docker-entrypoint-initdb.d/
COPY 02_createTriggerAndView.sql /docker-entrypoint-initdb.d/
COPY 03_insertData.sql /docker-entrypoint-initdb.d/
ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=mydb
EXPOSE 5432
